# This file contains values from Cookiecutter

default_context:
  project_name: "exqaliber"
  project_description: "Sequential amplitude estimation algorithms."
  organization: "Cambridge Consultants"
  license: "MIT"
  minimal_python_version: 3.10
  github_name: "jlt3"
  email: "joseph.tedds@cambridgeconsultants.com"
  version: "0.1.0"
  line_length: "79"
  create_example_template: "none"
